version: 2.1
orbs:
  # for setting up the server we need in orbs (node.js, AWS, EB)
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    # this is the docker image that we will use
    docker:
      - image: "cimg/base:stable"
    steps:
      # we setting up  all software used in our pipeline process
      - node/install
      - node/install-yarn
      - checkout
      - aws-cli/setup
      - eb/setup
      # this job for run the command for: install all dependancies of frontend
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      # this job for run the command for: install all dependancies of backend
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      # this job for run the command for: build the frontend
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      # this job for run the command for: build the backend
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      # this job for run the command for: test the frontend
      - run:
          name: Front-End test
          command: |
            npm run frontend:test
      # this job for run the command for: test the bacend
      - run:
          name: Back-End test
          command: |
            npm run backend:test
      # this job for run the command for: deploy the frontend
      - run:
          name: Deploy frontend
          command: |
            npm run frontend:deploy
      # this job for run the command for: deploy the backend
      - run:
          name: Deploy backend
          command: |
            npm run backend:deploy
workflows:
  my-App: # workflow label
    jobs:
      # this make the trigger run only if I push to main branch
      - build:
          filters:
            branches:
              only:
                - master
