
version: 2.1
orbs:
  # for setting up the server we need in orbs (node.js, AWS, EB)
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      # we setting up  all software used in our pipeline process 
      - node/install
      - node/install-yarn
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End test
          command: |
            npm run frontend:test
      - run:
          name: Back-End test
          command: |
            npm run backend:test
      - run:
          name: Deploy frontend
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy backend
          command: |
            npm run backend:deploy
workflows:
  my-App:  # workflow label
    jobs:
    # this make the trigger run only if I push to main branch
      - build:  
          filters:
            branches:
               only:                
                  - main

